### ISSUE TITLE
Synced Settings were wiped out after updating to 6.5.0!!!

### ISSUE THREAD

**Issue by grudge61** [ChrisRM/material-theme-jetbrains#1760]
### Summary

java.lang.NoClassDefFoundError: org/fest/util/Lists
	at com.mallowigi.idea.MTCloudProvider.appendClassesToStream(MTCloudProvider.java:39)
	at com.intellij.cloudConfig.CloudConfigManager.initClasses(CloudConfigManager.java:393)
	at com.intellij.cloudConfig.CloudConfigManager.getConfigInfos(CloudConfigManager.java:423)
	at com.intellij.cloudConfig.CloudConfigManager.loadStates(CloudConfigManager.java:446)
	at com.intellij.cloudConfig.CloudConfigManager.setStreamProviderBeforeStart(CloudConfigManager.java:297)
	at com.intellij.cloudConfig.CloudConfigManager.beforeApplicationLoaded(CloudConfigManager.java:273)
	at com.intellij.idea.ApplicationLoader.initConfigurationStore(ApplicationLoader.kt:417)
	at com.intellij.idea.ApplicationLoader$registerRegistryAndInitStore$1.apply(ApplicationLoader.kt:296)
	at com.intellij.idea.ApplicationLoader$registerRegistryAndInitStore$1.apply(ApplicationLoader.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at com.intellij.idea.ApplicationLoader.registerRegistryAndInitStore(ApplicationLoader.kt:288)
	at com.intellij.idea.ApplicationLoader.startApp(ApplicationLoader.kt:121)
	at com.intellij.idea.ApplicationLoader.executeInitAppInEdt(ApplicationLoader.kt:66)
	at com.intellij.idea.ApplicationLoader.access$executeInitAppInEdt(ApplicationLoader.kt:1)
	at com.intellij.idea.ApplicationLoader$initApplication$1$1.run(ApplicationLoader.kt:363)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.fest.util.Lists PluginClassLoader(plugin=PluginDescriptor(name=Material Theme UI, id=com.chrisrm.idea.MaterialThemeUI, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2021.1/plugins/Material Theme UI, version=6.5.0, package=null), packagePrefix=null, instanceId=75, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 29 more

### Steps to reproduce (if needed)

During work time

### Environment

PhpStorm 2021.1.2
Build #PS-211.7142.44, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), zielu.gittoolbox (203.5.8), intellij.prettierJS (211.7142.13), aws.toolkit (1.26-211), com.chrisrm.idea.MaterialThemeUI (6.5.0), de.espend.idea.laravel (0.15.4), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), ru.adelf.idea.dotenv (2021.1)

**Comment by TimVerheul** [comment]
Also got this when trying to run my code.

**Comment by mallowigi** [comment]
reproduced.

**Comment by mallowigi** [comment]
aaaaaand released. Please update.

**Comment by mallowigi** [comment]
IMPORTANT: If you used Sync Settings, the previous version might have wiped up your settings... I'm truly sorry for the inconvenience :'(

**Comment by mallowigi** [comment]
Im deleting this version. I need to conduct more tests regarding this settings getting wiped out. Sorry for the trouble, stay in touch for future updates.

**Comment by mallowigi** [comment]
**Important**: From what I heard, this update might have wiped out what was in the sync settings cloud. I'm truly sorry about that, I hope you had a backup somewhere.

If it happened to you, please do this to restore your cloud settings:
- Turn off Sync Settings
- Import your backup
- Turn on sync settings back and select "Keep local files"
- Let your imported settings be synced in the cloud.

Again, sorry about that, that was a dumb mistake which somehow had very bad repercussions.

**Comment by mallowigi** [comment]
Since the issue has been solved I should close this issue.
